# Generated by Django 5.0.6 on 2024-06-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealership_name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='dealer_profiles/')),
            ],
        ),
    ]
